![imagen](./img/ejercicios.png)

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [1]:
import numpy as np

In [3]:
my_array = np.arange(0,10)
my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
my_array[1::2][::-1]

array([9, 7, 5, 3, 1])

## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [5]:
my_array[8:6:-1]

array([8, 7])

## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [6]:
my_array[2::-1]

array([2, 1, 0])

## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [8]:
my_matrix = np.arange(1,21).reshape(4,5)
my_matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [10]:
my_matrix[::-1,::-1]

array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [18]:
my_matrix[0:2,0:2]

array([[1, 2],
       [6, 7]])

## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [21]:
my_matrix[0:4:2, 0:5:2]

array([[ 1,  3,  5],
       [11, 13, 15]])

## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [23]:
my_matrix[0:3, :][:,::-1]

array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])

## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [24]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

In [28]:
x[x == "Loro"]

array(['Loro', 'Loro'], dtype='<U5')

In [27]:
x[0::3]

array(['Loro', 'Loro'], dtype='<U5')

## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [29]:
np.arange(0,20).reshape(2,5,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [30]:
my_matrix[::-1,::-1]

array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [32]:
array_once = np.full((10,),0)
array_once

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [36]:
array_once.nbytes

80

In [35]:
array_once[3] = 1
array_once

array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0])

## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [39]:
vector = np.arange(10,50)
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [40]:
vector[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

## Ejericio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

In [43]:
vector_trece = np.array([1,2,0,0,4,0])
vector_trece

array([1, 2, 0, 0, 4, 0])

In [49]:
# Ponemos el cero porque el resultado es una tupla y solo queremos los índices
np.nonzero(vector_trece)[0]

array([0, 1, 4])

In [50]:
np.nonzero??

Signature:       np.nonzero(a)
Call signature:  np.nonzero(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function nonzero at 0x000002C7570EF490>
File:            c:\users\marta\miniconda3\envs\data_analysis.env\lib\site-packages\numpy\_core\fromnumeric.py
Source:         
@array_function_dispatch(_nonzero_dispatcher)
def nonzero(a):
    """
    Return the indices of the elements that are non-zero.

    Returns a tuple of arrays, one for each dimension of `a`,
    containing the indices of the non-zero elements in that
    dimension. The values in `a` are always tested and returned in
    row-major, C-style order.

    To group the indices by element, rather than dimension, use `argwhere`,
    which returns a row for each non-zero element.

    .. note::

       When called on a zero-d array or scalar, ``nonzero(a)`` is treated
       as ``nonzero(atleast_1d(a))``.

       .. deprecated:: 1.17.0

          Use `atleast_1d` explicitly if this behavior is de

## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [52]:
my_matrix_catorce = np.random.rand(10,10)
my_matrix_catorce

array([[2.06879758e-01, 2.50192948e-02, 2.17535143e-02, 1.26294575e-02,
        9.57757426e-01, 9.81186405e-01, 9.32847357e-04, 3.72443091e-01,
        8.41261519e-01, 5.93543450e-01],
       [7.86624028e-01, 8.49757617e-01, 4.70420747e-01, 5.13613039e-01,
        6.62502707e-01, 3.18948251e-01, 3.45795365e-02, 9.06349217e-01,
        2.11250287e-02, 8.30223741e-01],
       [8.79203343e-01, 9.01359657e-01, 3.34415107e-01, 1.73362826e-01,
        6.91672415e-01, 9.23972084e-01, 7.84336167e-01, 2.61903560e-01,
        4.97163029e-01, 1.66102974e-01],
       [9.57921638e-01, 1.59611792e-01, 1.87439052e-01, 7.63278691e-01,
        9.85611603e-02, 3.30474354e-01, 5.96446913e-01, 3.99397240e-01,
        2.71237173e-01, 5.63324867e-01],
       [9.23107157e-01, 5.93144177e-01, 5.17901149e-01, 3.99355712e-01,
        6.59498173e-01, 5.48437467e-01, 9.37862124e-01, 1.47912837e-01,
        9.80333612e-01, 8.53737539e-01],
       [9.28923345e-02, 3.07558086e-01, 9.95716939e-01, 9.06539143e-01,
   

In [53]:
np.max(my_matrix_catorce)

np.float64(0.9957169393210571)

In [54]:
np.min(my_matrix_catorce)

np.float64(0.0009328473574669038)

## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [56]:
vector_quince = np.random.randint(0,100,(30,))
vector_quince

array([28, 27, 52, 16, 76, 80, 46, 70, 27, 13, 36, 48, 10, 27, 53, 51, 37,
       17, 12, 87, 40, 73, 63, 97,  1, 42, 61, 18, 55, 64], dtype=int32)

In [57]:
np.mean(vector_quince)

np.float64(44.233333333333334)

## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quiras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [77]:
my_array16 = np.full((10,10),0)
my_array16[0] = 1
my_array16[-1] = 1
my_array16[:,0] = 1
my_array16[:,-1] = 1
my_array16
my_array16

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

## Ejercicio 17
Crea una mtriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [84]:
my_array17 = np.full((8,8),0)
my_array17[0::2,1::2]=1
my_array17[1::2,0::2] = 1
my_array17

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [93]:
array18 = np.array([[0,1,0,1,0,1,0,1],[1,0,1,0,1,0,1,0]])
np.tile(array18,(4,1))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [85]:
np.tile??

Signature:       np.tile(A, reps)
Call signature:  np.tile(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function tile at 0x000002C75727DFC0>
File:            c:\users\marta\miniconda3\envs\data_analysis.env\lib\site-packages\numpy\lib\_shape_base_impl.py
Source:         
@array_function_dispatch(_tile_dispatcher)
def tile(A, reps):
    """
    Construct an array by repeating A the number of times given by reps.

    If `reps` has length ``d``, the result will have dimension of
    ``max(d, A.ndim)``.

    If ``A.ndim < d``, `A` is promoted to be d-dimensional by prepending new
    axes. So a shape (3,) array is promoted to (1, 3) for 2-D replication,
    or shape (1, 1, 3) for 3-D replication. If this is not the desired
    behavior, promote `A` to d-dimensions manually before calling this
    function.

    If ``A.ndim > d``, `reps` is promoted to `A`.ndim by prepending 1's to it.
    Thus for an `A` of shape (2, 3, 4, 5), a `reps` of (2, 2) is treated 

## Ejercicio 19
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [95]:
matrix19 = np.random.rand(5,5)
matrix19

array([[0.955901  , 0.28684665, 0.02414236, 0.16361383, 0.82601591],
       [0.96003535, 0.70003653, 0.8000682 , 0.7680094 , 0.48996001],
       [0.51055538, 0.48552108, 0.11571248, 0.41096496, 0.35534033],
       [0.18236672, 0.55230772, 0.53735053, 0.53656921, 0.96622677],
       [0.76598958, 0.37397878, 0.52794626, 0.16876461, 0.52203812]])

In [99]:
matrix19_normalizada = (matrix19 - np.mean(matrix19))/np.std(matrix19)                                                  
matrix19_normalizada

array([[ 1.62587046, -0.8664984 , -1.84512741, -1.32556669,  1.14202106],
       [ 1.64127181,  0.67272122,  1.04536033,  0.92593452, -0.1098582 ],
       [-0.0331361 , -0.12639415, -1.50400933, -0.40413144, -0.61134495],
       [-1.2557082 ,  0.12240019,  0.06668151,  0.06377093,  1.66433614],
       [ 0.91841028, -0.5419128 ,  0.0316486 , -1.30637894,  0.00963954]])

## Ejercicio 20
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [103]:
vector20 = np.arange(0,11)
vector20

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [104]:
vector20[3:9] = -1
vector20

array([ 0,  1,  2, -1, -1, -1, -1, -1, -1,  9, 10])

In [106]:
vector20[3:9] = False
vector20

array([ 0,  1,  2,  0,  0,  0,  0,  0,  0,  9, 10])

## Ejercicio 21
#### Bonus track. Mini hundir la flota
1. Crea un tablero de 10x10 relleno del carácter espacio ( ).
2. Posiciona un par de barcos en [(0,1), (1,1)] y [(1,3), (1,4), (1,5), (1,6)]. Los barcos serán Os mayúsculas. Como ves, un barco de dos posiciones de eslora y otro de cuatro.
3. Recibe un disparo en uno de los barcos, sustituyendo la O por una X
4. Recibe un disparo en agua, sustituyendo uno de los espacios por un guión: -
5. Ignorando los disparos recibidos, ahora prueba a posicionar otro barco de 4 posiciones dentro del tablero, pero **de manera ALEATORIA.**

**TIP apartado 5**: El barco tendrá una posición inicial aleatoria dentro del tablero, y una orientación también aleatoria (N,S,E,O).

Por ejemplo, si tu posicion inicial fuese (5,0) y la orientación O, no podrias ponerlo porque se sale del tablero. Ahora bien, si fuese orientación este, si podrías, y ocuparía las posiciones [(5,0), (5,1), (5,2), (5,3)]. Por tanto tendrás que iterar con un bucle si es posible encajar el barco en el tablero, y el bucle terminará cuando lo consigas encajar. **Ojo con las posiciones donde ya hay barco!!!**

Usa `import random` para elegir las coordenadas aleatorias.

In [107]:
# Creamos el tablero
tablero = np.full((10,10)," ")
tablero

array([[' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ']], dtype='<U1')

In [110]:
# Posicionamos los barcos
tablero[0:2, 1] = "O"
tablero[1, 3:7] = "O"

tablero

array([[' ', 'O', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', 'O', ' ', 'O', 'O', 'O', 'O', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ']], dtype='<U1')

In [112]:
# Recibimos un disparo en uno de los barcos
tablero[1,3] = "X"
tablero


array([[' ', 'O', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', 'O', ' ', 'X', 'O', 'O', 'O', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ']], dtype='<U1')

In [113]:
# Recibimos un disparo en el agua
tablero[9,3] = "-"
tablero

array([[' ', 'O', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', 'O', ' ', 'X', 'O', 'O', 'O', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', '-', ' ', ' ', ' ', ' ', ' ', ' ']], dtype='<U1')

In [114]:
# Posicionamos barco de manera aleatoria


SyntaxError: expected ':' (2994583331.py, line 2)

ValueError: cannot reshape array of size 1 into shape (10,10)