![imagen](./img/ejercicios.png)

## Ejercicio 1
Importa el módulo de `numpy` y obtén su versión.

In [2]:
import numpy as np
np.__version__

'2.1.2'

## Ejercicio 2
Crea un array de una dimensión que vaya de 0 a 9. Llamalo `my_array`

In [5]:
my_array = np.array([0,1,2,3,4,5,6,7,8,9])
my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Ejercicio 3
Crea un array 3x3, que sea todo a True

In [6]:
my_array2 = np.full((3,3), True)
my_array2

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## Ejercicio 4
Extrae todos los impares de `my_array`

In [7]:
my_array[1::2]

array([1, 3, 5, 7, 9])

In [8]:
impares = []
for num in my_array:
    if num%2 != 0:
        impares.append(int(num))

print(impares)

[1, 3, 5, 7, 9]


In [9]:
mascara = my_array%2 !=0
my_array[mascara]

array([1, 3, 5, 7, 9])

## Ejercicio 5
En un nuevo array, sustituye todos los impares de `my_array` por -1

In [11]:
my_array[1::2] = -1
my_array

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [32]:
for index,num in enumerate(my_array):
    if num%2 != 0:
        my_array[index] = -1

my_array

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

## Ejercicio 6
En un nuevo array, sustituye todos los impares de `my_array` por -1. Esta vez usa `where`

In [80]:

my_array3 = np.array([0,1,2,3,4,5,6,7,8,9])
# Te devuelve si no cumple la condición
condicion = (my_array3)%2 == 0
np.where(condicion,my_array3,-1)


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

## Ejercicio 7
Convierte `my_array` en un nuevo array de dos dimensiones mediante `reshape`.

In [36]:
my_array = np.array([0,1,2,3,4,5,6,7,8,9])
my_array.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Ejercicio 8
Concatena los siguientes arrays verticamente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [44]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.concatenate((a,b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Ejercicio 9
Concatena los siguientes arrays horizontamente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [45]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.concatenate((a,b), axis = 1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Ejercicio 10
Encuentra todos los elementos en común entre ambos arrays. [Para ello usa el método `intersect1d`](https://numpy.org/doc/stable/reference/generated/numpy.intersect1d.html)

```Python
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

In [13]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

In [14]:
set(a).intersection(set(b))

{np.int64(2), np.int64(4)}

## Ejercicio 11
Obtén la documentación acerca de la función `concatenate`

In [50]:
np.concatenate??

Call signature:  np.concatenate(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <built-in function concatenate>
Docstring:      
concatenate(
    (a1, a2, ...), 
    axis=0, 
    out=None, 
    dtype=None, 
    casting="same_kind"
)

Join a sequence of arrays along an existing axis.

Parameters
----------
a1, a2, ... : sequence of array_like
    The arrays must have the same shape, except in the dimension
    corresponding to `axis` (the first, by default).
axis : int, optional
    The axis along which the arrays will be joined.  If axis is None,
    arrays are flattened before use.  Default is 0.
out : ndarray, optional
    If provided, the destination to place the result. The shape must be
    correct, matching that of what concatenate would have returned if no
    out argument were specified.
dtype : str or dtype
    If provided, the destination array will have this dtype. Cannot be
    provided together with `out`.

    .. versionadded:: 1.20.0

casting 

## Ejercicio 12
Crea un array unidimensional que vaya del 0 al 9. Llámalo `my_array`. 
1. Multiplica cada uno de los elementos de `my_array` por 10, en un nuevo array
2. Accede al primer elemento del array
3. Accede al último elemento del array
4. Imprime por pantalla los numeros del 1 al 7

In [52]:
my_array = np.array([0,1,2,3,4,5,6,7,8,9])
my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
my_array10 = my_array*10
my_array10

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [55]:
print(my_array[0])
print(my_array[1:8])

0
[1 2 3 4 5 6 7]


## Ejercicio 13
Crea un array manualmente de tres filas por tres columnas. Llámalo `my_matrix`

In [58]:
my_matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
my_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Ejercicio 14
Obtén la siguiente secuencia:

```Python
[ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49]
```

In [60]:
np.arange(1,50,3)

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49])

## Ejercicio 15
Obtén la siguiente secuencia

```Python
[4., 3.75, 3.5 , 3.25, 3.  , 2.75, 2.5 , 2.25, 2., 1.75, 1.5 ,1.25]
```

In [61]:
np.arange(4,1,-0.25)

array([4.  , 3.75, 3.5 , 3.25, 3.  , 2.75, 2.5 , 2.25, 2.  , 1.75, 1.5 ,
       1.25])

## Ejercicio 16
Lee la imagen "numpy.png"

![imagen](./img/numpy.png)

In [19]:
import matplotlib.pyplot as plt

imagen = plt.imread("./img/numpy.png")

## Ejercicio 17
Crea un array de 4x1. A continuación convierte el array a un 2x2

In [20]:
new_array = np.array([[1],[2],[3],[4]])
print(new_array)

new_array.reshape(2,2)


[[1]
 [2]
 [3]
 [4]]


array([[1, 2],
       [3, 4]])

## Ejercicio 18
Crea una secuencia aleatoria. La secuencia se tiene que componer de 4 matrices de 5x3. Serían 3 dimensiones diferentes.

In [73]:
np.random.randint(1,10,(4,5,3))

array([[[9, 1, 5],
        [5, 6, 2],
        [2, 2, 1],
        [9, 5, 1],
        [3, 7, 4]],

       [[1, 2, 5],
        [7, 6, 6],
        [5, 6, 8],
        [1, 1, 7],
        [6, 5, 6]],

       [[5, 3, 2],
        [7, 2, 8],
        [1, 7, 3],
        [9, 3, 9],
        [9, 3, 6]],

       [[1, 8, 5],
        [4, 9, 9],
        [2, 1, 7],
        [1, 3, 1],
        [8, 5, 6]]], dtype=int32)

In [3]:
np.random.rand(4,5,3)

array([[[0.47193504, 0.99171692, 0.39546778],
        [0.40441499, 0.56154285, 0.78938417],
        [0.39202385, 0.7947092 , 0.17454391],
        [0.99096002, 0.35506433, 0.79293797],
        [0.46755322, 0.67500944, 0.32467882]],

       [[0.64183662, 0.35714294, 0.3462551 ],
        [0.44471975, 0.62035936, 0.56403485],
        [0.52231697, 0.25985808, 0.80957848],
        [0.39065601, 0.39476974, 0.89235089],
        [0.22131115, 0.72465077, 0.80674818]],

       [[0.46524252, 0.26247132, 0.96283355],
        [0.37604606, 0.94285788, 0.14998504],
        [0.39301193, 0.75508657, 0.25195882],
        [0.92259272, 0.89545671, 0.41607797],
        [0.7817735 , 0.67406574, 0.8010237 ]],

       [[0.67143163, 0.85478188, 0.72263971],
        [0.14252074, 0.26362531, 0.200797  ],
        [0.2974423 , 0.10635609, 0.801597  ],
        [0.50679838, 0.40715837, 0.02421885],
        [0.1429153 , 0.56746389, 0.99570276]]])

## Ejercicio 19
Crea una matriz de 10x1, toda ella compuesta por `False`. Después transformalo en un 2x5

In [71]:
matriz_19 = np.full((10,1), False)
print(matriz_19)
matriz_19.reshape(2,5)

[[False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]]


array([[False, False, False, False, False],
       [False, False, False, False, False]])

## Ejercicio 20
Dado el siguiente array

```Python
x =np.random.randint(10, 20, size = (5,2,6))
```

1. ¿Cuántos elementos tiene el array?
2. ¿Cuántas dimensiones?
3. ¿Cuántos elementos tiene cada dimensión?

In [76]:
x =np.random.randint(10, 20, size = (5,2,6))
print(x.size)
print(x.ndim)
print(x.shape)


60
3
(5, 2, 6)
